import { Download, FileText, Zap } from 'lucide-react';

const REPORTS = [
  { title: 'Complete Career Report', desc: 'Full analysis: scores, gaps, roadmap, recommendations', icon: '📋', pages: 12 },
  { title: 'Skill Gap Analysis', desc: 'Detailed skill comparison and learning priorities', icon: '🎯', pages: 4 },
  { title: 'Company Readiness Report', desc: 'Per-company preparation status and interview tips', icon: '🏢', pages: 8 },
  { title: 'Learning Roadmap PDF', desc: '90-day personalized learning plan with resources', icon: '🗺️', pages: 6 },
  { title: 'Interview Preparation Kit', desc: 'Question bank, tips, and mock interview guide', icon: '💬', pages: 15 },
];

export default function ReportsPage() {
  const handleDownload = (title: string) => {
    const content = `SKILLGAP AI - ${title}\nGenerated: ${new Date().toLocaleDateString()}\n\nThis report has been generated by SkillGap AI.\nAll analysis is privacy-first and browser-based.\n\n[Full report content would be rendered here in production]`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/\s+/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div>
        <div className="section-label w-fit">📥 PDF Reports</div>
        <h2 className="text-2xl font-display font-bold text-white">Export Your Reports</h2>
        <p className="text-slate-400 mt-1">Download comprehensive career intelligence reports</p>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {REPORTS.map(report => (
          <div key={report.title} className="glass-card p-5 hover:scale-[1.02] transition-all">
            <div className="flex items-start gap-3 mb-4">
              <div className="text-3xl">{report.icon}</div>
              <div>
                <h3 className="text-sm font-bold text-white">{report.title}</h3>
                <p className="text-xs text-slate-400 mt-0.5">{report.desc}</p>
                <span className="badge-blue mt-2">{report.pages} pages</span>
              </div>
            </div>
            <button onClick={() => handleDownload(report.title)} className="btn-primary w-full text-sm flex items-center justify-center gap-2">
              <Download size={14} />Download Report
            </button>
          </div>
        ))}
      </div>
      <div className="glass-card p-4 flex items-center gap-3" style={{ background: 'rgba(0,255,136,0.05)', border: '1px solid rgba(0,255,136,0.15)' }}>
        <Zap size={14} className="text-green-400" />
        <p className="text-xs text-slate-400">All reports are generated locally. Your data never leaves your device.</p>
      </div>
    </div>
  );
}
